stages:
  - build
  - deploy

default:
    image: docker:19.03.10
    services:
      - docker:dind
    tags:
      - ecs,ecr

variables:
    REPOSITORY_URL: 551328564212.dkr.ecr.us-east-1.amazonaws.com/gitlab-ecs-app
    REPOSITORY_BASE: 551328564212.dkr.ecr.us-east-1.amazonaws.com
    TASK_DEFINITION_NAME:  gitlab-ecs-app
    CLUSTER_NAME:  gitlab-cluster
    SERVICE_NAME: gitlab-ecs-app

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
