stages:
  - build
  - deploy

default:
    image: docker:19.03.10
    services:
      - docker:dind
    tags:
      - ecs,ecr

variables:
    REPOSITORY_URL: 213932411534.dkr.ecr.us-west-2.amazonaws.com/gitlab-ecs-app
    REPOSITORY_BASE: 213932411534.dkr.ecr.us-west-2.amazonaws.com
    TASK_DEFINITION_NAME:  ecs-demo-task
    CLUSTER_NAME:  container-demo
    SERVICE_NAME: my-demo-ecs

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
